### ISSUE TITLE
feathers generate connection

### ISSUE THREAD

**Issue by ntoskrnl-exe** [feathersjs/cli#203] opened 2019-12-13 14:49 UTC
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
./node_modules/@feathersjs/cli/bin/feathers.js generate connection

I expect to see a MongoDB option. This was working in earlier versions, but haven't touched this project in couple of months. Upgrading everything. 

So maybe I have done something wrong.

### Actual behavior
I do not see mongodb option. I see MySQL, PostgreSQL, SQLite and SQLServer

### System configuration

**Module versions** (especially the part that's not working):

./node_modules/@feathersjs/cli/bin/feathers.js --version

4.2.3

**NodeJS version**:

13.3.0

**Operating System**:

Ubuntu Linux

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment] 2019-12-13 16:43
Duplicate of https://github.com/feathersjs/generator-feathers/issues/499. For now just generate the service which will let you select the db you want and generate the connection if it doesn't exist.

**Closed by daffl** 2019-12-13 16:43 UTC
