### ISSUE TITLE
Feathers CLI command producing strange output.

### ISSUE THREAD

**Issue by saul-avikar** [feathersjs/cli#285] opened 2022-01-09 22:39 UTC
### Steps to reproduce

1. Install npm and nodejs using nvm.
2. Install the feathers cli command as per the [docs](https://docs.feathersjs.com/guides/basics/generator.html#generating-the-application). (`npm install @feathersjs/cli -g`)
3. Run any feathers command:
  - `feathers`
  - `feathers --version`
  - `feathers generate app`

### Expected behavior
The feathers command should produce the result as described in the documentation.

### Actual behavior
I get the following output on the command line:
```
undefined
undefined
undefined
                                   !             H|H|H|H|H           H__________________________________             H|§|§|§|H           H|* * * * * *|---------------------|             H|§|∞|§|H           H| * * * * * |---------------------|             H|§|§|§|H           H|* * * * * *|---------------------|             H|H|H|H|H           H| * * * * * |---------------------|             H|H|H|H|H           H|---------------------------------|          ===============        H|---------------------------------|            /| _   _ |          H|---------------------------------|            (| O   O |)          H|---------------------------------|            /|   U   |          H-----------------------------------             |  =/  |           H              _..._/            H              _|I/|_            H      _______/| H |/_______    H     /           / /          H    |          | | /         |  H    |          ||o||          |  H    |    |     ||o||     |    |  H    |    |     ||o||     |    |  H   Carl Pilcher  
t̎ͤ͒eͫ̂ ҉̷͇̘͉sͥ͛͊t́̓̂ǐͬn̓̑̈̈g͐̈ ҉̧͢ ͪ͛t̆ͫeͫ̆ŝ̿ͮt̄̑iͨ̅n̎̂g̽̇ ҉͇͖̰ ̑̅t̐̾̒eͯ͑s̄ͭͣ ҉̠͈͘t́̅̿iͪ͂n̽ͧ ҉̼̰g̃̃ ̀ͭ̈t̒̈̚eͦ̏s̏̓tͫ̅i͆̚n̈̅g̅ͤ ͧ͂tͨ̾e͑͂sͯ͑̌t̊͒ï̃n͆̾g͗ͧ ̅̈ ҉̛͞t̒̿͑e̓̈s̔̌t́ͯǐ̉n̾g͂ ̈ͯt͆͂eͯ͂s͛̔t͊̆̏iͪ̚n̅̄g͛̓
t͛͌eͪ͊s̏ͦt͒̋iͥ̚n̈ͮ ҉̛͘gͫ̑͂ ҉̰͠ ̓̀́̂ẗ͐ ҉́͢eͯ͐͊s̈̈tͤ̍iͥ̆ͦ ҉͇̹̝̳ṅͯ ҉̴͠ġ̑ ̃͐ ҉̮̠̫tͮ̓ëͪͣsͬͮ ҉̧̨t̔ͩȋ͋ ҉͟͠n͆̇g͌ͯ ̎͐t́̊͂̒ĕ̿s͂̉t̍̓i̍ͯͫń̏̒gͣ ͂̄t̀͐̄e͑͂sͤͮ͛t̾͂i͑͌ͪ ҉̲͜ñ͗͒g͛̈ ͗̒̐t̃̇ ҉̣̜̕͘e͒͗sͩ̓t̓͊i͆́n̿̐g͐͒ ͧ̃ͥt͋̒ ҉̕ ҉̴͜ě̈ͨṡͪt́̓̂iͬ͂nͣͮgͥ̔
t̊͆̒êsͯ̀t̒̀iͥ̆nͨ͐g̓͊̃ ͆̓tͪ͌e̽̒s̐̍ͮtͫ̾iͫ̾͊n̒ͧͦg͐ ̈̏t̂̓ȇ̾ͯs͌͛t̆͊̈ǐ̆͛̚n̂̀́gͫͨ ̒̑t̒͆e͌̍s̔͛tͪ̉i̽ͯ̈n̍̑ ҉̘͜g͗̓ ͥ͋tͨ̋eͧ̊s͆̉t̅́i̾́̍n͊̉ͭ̌gͩͩ ͨ̓t̓̽̅e͑̌s̐ͮtͨ̃͒i͂͛n̑̓ǧ̆͑ ͐ͤtͦ́͐eͥ͊̾sͯ̍ͧ͆tͥ̾͒iͣͫnͭ͗͆g͗͑
t̎̐eͣͬsͣͣtͩ̚i͗̾ ҉̸̢ǹ̂g͋̌ ҉̝̞͖ ͮ̐ͯ ҉͚͜ẗ̚e̽͛s̀̊t̒͗i͂ͪͣn̅ͫgͫ̃ͭ ͂̽t̅̌ ҉̛͡eͥs͆̓̉t̊͆ ҉̷͎̗̘i̍͆̐nͩ̅g̾̌ ̅̉̃t͂͌ẽ̃s̓̎t̃͑ĩ͊n͆̈̓g̎̓ ̉ͨ̐ ҉̰͈͚t͂̅èͬ̐s͆ͤt̄̒͐̂i̐̓nͬͦg̾͆ ̎̓ ҉̛͜t̊̏ë̃s͒ͤ ҉͔̹́tͤͥi̎ͣ ҉̲͜nͪ͐g̓̀ ҉̫ ̆̇t͋͒e͐ͩs̾ͭtͪ̈ȋ͛n͋͌̇g̉̑
```

The lines that appear to say "testing" (or variations of it) repeat indefinitely.

### System configuration

**NodeJS version**:
I have tried the following versions:
- v17.3.0
- v14.15.4
- v10.24.1

**Operating System**:
Linux Mint 20.1 Cinnamon

**Comment by Siderali** [comment] 2022-01-09 23:19
I confirm having the same issue, tested on 2 different computers. Problem seems to be related to @facebook/jscodeshift

**Comment by liquidautumn** [comment] 2022-01-09 23:38
This is root cause: https://github.com/Marak/colors.js/issues/285
Basically, colors maintainer intentionally published compromised package breaking lots of dependent libs.
jscodeshift have PR fixing this issue https://github.com/facebook/jscodeshift/pull/472 which is not yet merged

**Comment by Siderali** [comment] 2022-01-09 23:56
Thanks @liquidautumn
I used the version 1.4.0 in my project and it works now.

**Comment by saul-avikar** [comment] 2022-01-10 00:14
Thanks @liquidautumn for clearing that up.

I'll close this issue when it gets handled.

In the meantime you can workaround the issue by adding `"colors": "1.4.0"` in the dependency list in **package.json** located at **~/.nvm/versions/node/v17.3.0/lib/node_modules/@feathersjs/cli** and then running `npm install` in that folder.

**Closed** 2022-01-10 17:18 UTC

**Comment by daffl** [comment] 2022-01-10 17:26
What crazyness. I am :100: % for having a discussion about the sustainability of the open source ecosystem because the way it is right now definitely isn't working but I don't think that throwing temper tantrums will get us there. Anyway, this should be fixed in the latest `@feathersjs/cli` now.
